import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {NavbarDemo} from "@/components/custom/Navbar";
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <EdgeStoreProvider>
      <body className="">
        <div className="bg-gray-200 mb-32">
        <NavbarDemo />
        </div>
        {children}
      </body>
      </EdgeStoreProvider>
    </html>
  );
}
